FROM hazelcast/hazelcast:latest
ADD /opt/hazelcast/cache-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/hazelcast/
ADD /opt/hazelcast/log4j.properties /opt/hazelcast/
ADD /opt/hazelcast/mu-cache-config.xml /opt/hazelcast/
ADD /opt/hazelcast/mu-client-config.xml /opt/hazelcast/
